### PR TITLE
Fix bug with tax queries by name with children

### LINKED ISSUE #103: Tax queries with `include_children => true` using the `name` field fail (in most cases)
### Description of the bug

As noted in #102, when a tax query has `include_children => true`, if the query is not already querying by term ID then the queried values (slugs, names, tt_ids) are converted to term IDs. However, if the original field was `name`, then [ES_WP_Query is sanitizing the name using the wrong function](https://github.com/alleyinteractive/es-wp-query/blob/1c7402b2f92fd9327e0189a39c85c2ab8b6ea2ec/class-es-wp-tax-query.php#L316). `sanitize_title_for_query()` will slugify the value, so the only names that will work in this query are those that happen to be in a valid "slug" format (lowercased and dashed). 

### Steps To Reproduce

1. Create a category with uppercase letters and/or spaces, e.g. `My Category`
2. Add a post in that category
3. Run an ES_WP_Query with a tax query like this:
    ```php
    'tax_query' => [
        [
            'taxonomy'         => 'category',
            'field'            => 'name',
            'terms'            => 'My Category',
            'include_children' => true,
        ],
    ],
    ```
4. Observe that the query produces no results. If you look at the DB queries run, you'll see a query for term ids where the category name is `my-category`.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mboynes**
This updates `ES_WP_Query::transform_query()` to match WordPress core's latest updates, which is a significant improvement.

Resolves #103.

### CODE REVIEW

File: class-es-wp-tax-query.php [hunk 1]
```diff
@@ -309,50 +307,56 @@ public function transform_query( &$query, $resulting_field ) {
 
 		$resulting_field = sanitize_key( $resulting_field );
 
-		// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared, WordPress.VIP.DirectDatabaseQuery.NoCaching, WordPress.VIP.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.DirectQuery
+		// Empty 'terms' always results in a null transformation.
+		$terms = array_filter( $query['terms'] );
```
Comment (kevinfodness) [inline class-es-wp-tax-query.php:311]: Recommend wrapping this in `array_values` so it's properly zero-indexed:
```suggestion
		$terms = array_values( array_filter( $query['terms'] ) );
```

**Review by kevinfodness — APPROVED** [review]
Minor fix-up, otherwise 🍣 - also I learned about the word "inexistent" and how it differs from "nonexistent"
